### PR TITLE
Add earthkit-transforms

### PR DESCRIPTION
**Pull request by EddyCMWF**
Add earthkit-transforms as a standard package

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/earthkit?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/earthkit?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/earthkit?pullRequest=58) it.</sub>

**Review by jameshawkes — APPROVED** [review]

**Comment by sandorkertesz** [comment]
@EddyCMWF 
Please also update __init__.py and the tests.  Consider renaming the issue to e.g. "Add earthkit-transforms".

**Comment by EddyCMWF** [comment]
> @EddyCMWF Please also update **init**.py and the tests. Consider renaming the issue to e.g. "Add earthkit-transforms".

done

**Comment by sandorkertesz** [comment]
Can it be merged now?

**Comment by iainrussell** [comment]
I think so, I'm happy to do it if you give me the 'ok'

**Pull request merged**
